### ISSUE TITLE
Nuxeo extent stats generation (for Schedule F)

### ISSUE THREAD

**Issue by christinklez** [ucldc/nuxeo-extent-stats#1]
Nuxeo extent stats folder: https://drive.google.com/drive/folders/1mqcerCqB1BpLlRj4J2JYMpmdSk8vAL0G

**Actively using Nuxeo**
- UCB
  - Slight discrepancies (~630 items dropped in UCB EDA folder)
- UCLA
  - Same extent as last year
- UCI
  - In-progress of generating
- UCM
  - In-progress of generating
- UCR
  - In-progress of generating
- UCSF
  - Slight discrepancies with some folders; ~2k item drop in one folder -- question out to UCSF: https://help.oac.cdlib.org/a/tickets/143042

**Not actively using Nuxeo**
- UCSD
- UCD
- UCSC
- UCSB
- UCOP

**Comment by barbarahui** [comment]
Reports for UCI and UCSF are available here:

https://drive.google.com/drive/folders/1SnPkuMZ7IlN79azOB61PHn3Coa0PF_bW

I'll add others as they're available.

**Comment by barbarahui** [comment]
I compared UCI and UCSF to last year's reports and the numbers are a lot lower. Does that seem right?
